// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrxBnUPXK6NIfjNSq3adPD0zcrsrq7Ko',
    appId: '1:402256954379:web:0d1d6160f707f0c190f30e',
    messagingSenderId: '402256954379',
    projectId: 'turf-flash',
    authDomain: 'turf-flash.firebaseapp.com',
    storageBucket: 'turf-flash.appspot.com',
    measurementId: 'G-PLKMH69R59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdY8UWI5yXCQchiRq8hycJATjzyvYQzwE',
    appId: '1:402256954379:android:574994d889bdf2a490f30e',
    messagingSenderId: '402256954379',
    projectId: 'turf-flash',
    storageBucket: 'turf-flash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplZLUyENjTec_rIITl6MVUdSekISXpas',
    appId: '1:402256954379:ios:e3ee4e67560e5f8690f30e',
    messagingSenderId: '402256954379',
    projectId: 'turf-flash',
    storageBucket: 'turf-flash.appspot.com',
    iosClientId: '402256954379-071bc82no0ckipnbs28abobrr9kbr4vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.turfFlash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBplZLUyENjTec_rIITl6MVUdSekISXpas',
    appId: '1:402256954379:ios:e3ee4e67560e5f8690f30e',
    messagingSenderId: '402256954379',
    projectId: 'turf-flash',
    storageBucket: 'turf-flash.appspot.com',
    iosClientId: '402256954379-071bc82no0ckipnbs28abobrr9kbr4vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.turfFlash',
  );
}
